// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.731
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Layout(stylesheets []string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"description\" content=\"Sittella Lab is a freelance web development business located in Perth, Western Australia\"><meta name=\"author\" content=\"Andrew Weymes\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><link rel=\"stylesheet\" href=\"/static/css/styles.css\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, stylesheet := range stylesheets {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<link rel=\"stylesheet\" href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(stylesheet)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/layout.templ`, Line: 13, Col: 44}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script src=\"/static/js/functions.js\"></script><title>Sittella Lab | Freelance Web Development | Perth, Western Australia</title></head><body><input id=\"nav\" type=\"checkbox\"> <label id=\"hamburger\" for=\"nav\"><div class=\"left\"><div class=\"line top\"></div><div class=\"line mid\"></div><div class=\"line bot\"></div></div><div class=\"right\"><div class=\"line top\"></div><div class=\"line mid\"></div><div class=\"line bot\"></div></div></label><nav><ul><li><a href=\"/\">Home</a></li><li><a href=\"/about\">About Me</a></li><li><a href=\"/contact\">Contact</a></li></ul></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<footer><h2>Let's Collaborate.</h2><div class=\"right\"><h3>Socials</h3><div class=\"socials\"><a href=\"https://au.linkedin.com/company/sittella-lab\" target=\"_blank\"><img src=\"/static/imgs/linkedin.svg\" alt=\"linkedin icon\"></a> <a href=\"https://github.com/dimmerz92\" target=\"_blank\"><img src=\"/static/imgs/github.svg\" alt=\"github icon\"></a></div></div><div class=\"right\"><h3>Send an Enquiry</h3><a class=\"cta-button\" href=\"/contact\">Work with me</a></div><div class=\"right\"><h3>Email Us</h3><a href=\"mailto:hello@sittellalab.com.au\">hello@sittellalab.com.au</a></div><p class=\"right\">Sittella Lab © 2024. All rights reserved.<br><a href=\"https://abr.business.gov.au/ABN/View?abn=69563454673\" target=\"_blank\">69 563 454 673</a></p></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
